name: Build HTML

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: install sphinx
        run: |
          sudo apt-get install plantuml
          pip3 install sphinx sphinx-autobuild sphinx_rtd_theme sphinxcontrib-plantuml PyYAML
          pip3 install -U git+https://github.com/CodevDynamics/sphinxcontrib-ros.git@master#egg=sphinxcontrib-ros

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          token: ${{ secrets.CODEVCI }}

      - name: Build HTML
        run: |
          make html

      - name: Upload HTML
        run: |
          aliyun configure set --profile default --region ${{ secrets.ALI_REGION_ID_OUTER }} --access-key-id ${{ secrets.ALI_ACCESS_KEY_ID }} --access-key-secret ${{ secrets.ALI_ACCESS_KEY_SECRET }}
          aliyun oss cp build/html/ oss://${{ secrets.ALI_DOC_BUCKET_NAME }}/ -r -f